/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javacoursework1555;


import static java.lang.Double.NEGATIVE_INFINITY;
import static java.lang.Double.NaN;
import static java.lang.Double.POSITIVE_INFINITY;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedList;
import static javacoursework1555.Functions.F1;
import static javacoursework1555.Functions.F2;
import static javacoursework1555.Functions.F3;
import static javacoursework1555.rootFinder.Bisection1;
import static javacoursework1555.rootFinder.Bisection2;
import static javacoursework1555.rootFinder.Bisection3;
import static javacoursework1555.rootFinder.MyWay;
import static javacoursework1555.rootFinder.MyWay2;
import static javacoursework1555.rootFinder.NR1;
import static javacoursework1555.rootFinder.NR2;
import static javacoursework1555.rootFinder.NR3;
import static javacoursework1555.rootFinder.Secant1;
import static javacoursework1555.rootFinder.Secant2;
import static javacoursework1555.rootFinder.Secant3;
import static javacoursework1555.subMenu.step1;

//import javacoursework1555.Plot2d;



/**
 *
 * @author barnabe
 */
public class GUI extends javax.swing.JFrame {

    /** Creates new form GUI */
    public GUI() {
        initComponents();
        
        //graph
        //int functionChoosen = 0;
        
       
        
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        
        
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        
//         while(n1 <= sizeX)
//         {
//             double a = X.get(n1);
//             X1[n1] = a;
//         
//         }
//         
//         while(n2 <= sizeY)
//         {
//             double b = X.get(n2);
//             Y1[n2] = b;
//         }
    


            

    }

    ArrayList<Double> Temp = new ArrayList<Double>();
    
    ArrayList<ArrayList<Double>> XY = new ArrayList<ArrayList<Double>>();
   
    ArrayList<Double> X = new ArrayList<Double>();
//    double [] X1;
//    int sizeX = X.size();
//    int n1 = 0;
    
   
    ArrayList<Double> Y = new ArrayList<Double>();
//    double [] Y1;
//    int sizeY = Y.size();
//    int n2 = 0;
//    
    
   
    // used for roots
    int[] FunctionChoosen = {0};
    
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame0");
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Result");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton3.setText("comfirm range");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButton2.setText("graph");
        jButton2.setActionCommand("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("f(x)=x-x^2");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("f(x)=ln(x+1)+1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("f(x)=e^x-3x");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-1", "0.5" , "0.50001", "0.49999" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "-1", "-1.0e-10" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.09", "1.1", "1.11" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton7.setText("f(x)=x-x^2");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("f(x)=ln(x+1)+1");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("f(x)=e^x-3x");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel1.setText("number of decimal :");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "not choosing", "1", "2", "3","4" ,"5"}));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel2.setText("choose your x : ");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "f(x)= x-x^2 ", "f(x)= ln(x+1)+1", "f(x)= e^x-3x"}));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jButton10.setText("ok");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField6)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton11.setText("Newton's Raphson");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Secant");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Bisection");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("MyWay");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton14)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addGap(109, 109, 109))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton13)
                    .addComponent(jButton12))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(171, 171, 171))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ///result
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        jPanel5.setVisible(false);
        
           
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    
   ///graph
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        jPanel2.setVisible(true);
        jPanel4.setVisible(false);
        
        
    
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
    
    
    
    /// GRAPH PART
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    
    /// comfirm range
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        jPanel3.setVisible(true);
        
        
        try      
        {            
            String g1 = jTextField1.getText(); 
            double d1 = Double.parseDouble(g1);
                         
            String g2 = jTextField2.getText();
            double d2 = Double.parseDouble(g2);
                        
                            
            //System.out.println(d1 +" "+ d2);    
            if(d1 > d2)     
            {           
                System.out.println("you can't enter an impossible range ");       
            }    
            else  
            {   
                Temp.add(0, d1);   
                Temp.add(1, d2); 
                System.out.println("range: for x:" + Temp.get(0) +" to x: "+ Temp.get(1));
            }
                    
        } catch(Exception e)
                    
        {
            System.out.println(" the number you entered isn't valide ");          
        }
    
            
        
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    
    ///graph - f(x) = x-x^2
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.out.println(" graph - f(x)= x-x^2");
        
        jPanel5.setVisible(true);
         
        int k = 1; 
        
        FunctionChoosen[0] = k;
              
        double k1 = Temp.get(0);  
        double k2 = Temp.get(1);
              
        System.out.println(k1 +" "+ k2);
              

        step1( k, k1, k2);  
        //System.out.println("print of step1() in GUI for f(x)=x-x^2   "+step1( k, k1, k2));
        XY = (step1(k, k1, k2));
        //System.out.println("print of XY list in GUI wich should be similar to step1() button selected f(x)=x-x^2  "+XY);
        X = XY.get(0);
        System.out.println("print of X list which should be similar to step1() first part button selected f(x)=x-x^2   "+X);
        Y = XY.get(1);
        System.out.println("print of Y list which should be similar to step1() first part button selected f(x)=x-x^2  "+Y);
        
        double minimumY = minY();
        System.out.println("min for f(x)=x-x^2 : "+minimumY);
        
        double maximumY = maxY();
        System.out.println("max for f(x)=x-x^2 : "+maximumY);
        
        
        
       //Plot2d T1 = new Plot2d(X1, Y1);
       
        
    }//GEN-LAST:event_jButton4ActionPerformed

    ///graph - f(x) = ln(x+1)+ 1
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
      jPanel5.setVisible(true);
        
      int k = 2; 
      
      FunctionChoosen[0] = k;
              
      double k1 = Temp.get(0);
      double k2 = Temp.get(1);
              
      //System.out.println(k1 +" "+ k2);
              
      step1( k, k1, k2);
      //System.out.println("print of step1() in GUI for f(x)=ln(x+1)+1   "+ step1( k, k1, k2));
      XY = (step1(k, k1, k2));
      //System.out.println("print of XY list in GUI wich should be similar to step1() button selected f(x)=ln(x+1)+1  "+XY);
      X = XY.get(0);
      System.out.println("print of X list which should be similar to step1() first part button selected f(x)=ln(x+1)+1   "+ X);
      Y = XY.get(1);
      System.out.println("print of Y list which should be similar to step1() first part button selected f(x)=ln(x+1)+1  "+Y);
      
        
        //double Ninfinite = Y.indexOf(NEGATIVE_INFINITY);//  value of infinity in Y for -infinty
        //double Pinfinite = Y.indexOf(POSITIVE_INFINITY);//  value of infinity in Y for +infinty
        
        double minimumY = minY();
        System.out.println("min: "+minimumY);
        double maximumY = maxY();
        System.out.println("max: "+maximumY);
        
        
        
//        if (Y.contains(NEGATIVE_INFINITY))
//        {
//        
//            System.out.println("min for f(x)=ln(x+1)+1 : "+NEGATIVE_INFINITY+"in X = "+X.get((int)Ninfinite));
//            minimumY = NEGATIVE_INFINITY;
//            maximumY = maxY();
//            System.out.println("max for f(x)=ln(x+1)+1 : "+maximumY);
//            
//        }else if (Y.contains(POSITIVE_INFINITY))
//        {
//        
//            System.out.println("max for f(x)=ln(x+1)+1 : "+POSITIVE_INFINITY+"in X = "+X.get((int)Pinfinite));
//            maximumY = POSITIVE_INFINITY;
//            minimumY = minY();
//            System.out.println("min for f(x)=ln(x+1)+1 : "+minimumY);
//        
//        }else if(Y.contains(NEGATIVE_INFINITY) || Y.contains(POSITIVE_INFINITY))
//        {
//        
//            System.out.println("min for f(x)=ln(x+1)+1 : "+NEGATIVE_INFINITY+"in X = "+Y.get((int)Ninfinite));
//            minimumY = NEGATIVE_INFINITY;
//            System.out.println("max for f(x)=ln(x+1)+1 : "+POSITIVE_INFINITY+"in X = "+Y.get((int)Pinfinite));
//            maximumY = POSITIVE_INFINITY;
//            
//        }else
//        {
//        
//            minimumY = minY();
//            System.out.println("min for f(x)=ln(x+1)+1 : "+minimumY);
//            
//            maximumY = maxY();
//            System.out.println("max for f(x)=ln(x+1)+1 : "+maximumY);
//        
//        }

        

        
        
        /*System.out.println(" X value of -Infinity: "+Ninfinite);
        System.out.println("Y value for Ninfinite: "+Y.get((int) Ninfinite));
        System.out.println(" X value of +Infinity: "+Pinfinite);*/
        
        

      
      
      //Plot2d T1 = new Plot2d(X1, Y1);
      
       
    }//GEN-LAST:event_jButton5ActionPerformed

    ///graph - f(x) = e^x-3x
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
       
        
        
        jPanel5.setVisible(true);
        
        int k = 3;
        
        FunctionChoosen[0] = k;
        
        double k1 = Temp.get(0);
        double k2 = Temp.get(1);
              
        //System.out.println(k1 +" "+ k2);
        step1( k, k1, k2);
        //System.out.println("print of step1() in GUI for f(x)=e^x-3x   "+ step1( k, k1, k2));
        XY = (step1(k, k1, k2));
        //System.out.println("print of XY list in GUI wich should be similar to step1() button selected f(x)=e^x-3  "+XY);
        X = XY.get(0);
        System.out.println("print of X list which should be similar to step1() first part button selected f(x)=e^x-3   "+ X);
        Y = XY.get(1);
        System.out.println("print of Y list which should be similar to step1() first part button selected f(x)=e^x-3  "+ Y);
        
        //Plot2d T1 = new Plot2d(X1, Y1);
        
        double minimumY = minY();
        System.out.println("min for f(x)=e^x-3 : "+minimumY);
        
        double maximumY = maxY();
        System.out.println("max for f(x)=e^x-3 : "+maximumY);      

        
        
    }//GEN-LAST:event_jButton6ActionPerformed

   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
   
    
    
/////////////////////////////////////////////////////////////////////////////////    
    
    
    
    
    
    
    
    ////RESULT PART
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

 
    
    ///result - f(x) = x-x^2 <- combobox1 is where the x asked are located
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //int n = 0 ;
        int n = (int) jComboBox1.getSelectedIndex();
        int Ndeci = (int) jComboBox4.getSelectedIndex();
        //System.out.println(n);
        
        if(n == 0)
        {
            Double  a = F1(-1.0);
            System.out.println(a);
            jTextField3.setText(decimalNumb(a, Ndeci));
            
            
        } else if(n == 1)
        {
            Double a = F1(0.5);
            System.out.println(a);
            jTextField3.setText(decimalNumb(a, Ndeci));
            
        } else if (n == 2)
        {
            Double a = F1(0.50001);
            System.out.println(a);
            jTextField3.setText(decimalNumb(a,Ndeci));
            
        } else if (n == 3)
        {
            Double a = F1(0.49999);
            System.out.println(a); 
            jTextField3.setText(decimalNumb(a, Ndeci));
            
        } else 
        {
            System.out.println(" it apear there is  a problem ");
        }
                
        
    }//GEN-LAST:event_jButton7ActionPerformed
     
    ///result - f(x) = ln(x+1)+ 1 <- combobox2 is where the x asked are located
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        int n = (int) jComboBox2.getSelectedIndex();
        int Ndeci = (int) jComboBox4.getSelectedIndex();
        //System.out.println(n);
        
        if(n == 0)
        {
            Double  a = F2(0.0);
            System.out.println(a);
            jTextField4.setText(decimalNumb(a, Ndeci));
            
        } else if(n == 1)
        {
            Double a = F2(-1.0);
            System.out.println(a);
            jTextField4.setText(decimalNumb(a, Ndeci));
            
        } else if (n == 2)
        {
                            /// -1.0e-10
            Double a = F2(-12.7182818285);
            System.out.println(a);
            jTextField4.setText(decimalNumb(a, Ndeci));
            
        }else 
        {
            System.out.println(" it apear there is  a problem ");
        }
          
        
    }//GEN-LAST:event_jButton8ActionPerformed
     
    ///result - f(x) = e^x-3x <- combobox3 is where the x asked are located
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
        // x choosen 
        int n = (int) jComboBox3.getSelectedIndex();
        
        //number of decimal 
        int Ndeci = (int) jComboBox4.getSelectedIndex();
        //System.out.println(n);
        
        if(n == 0)
        {
            Double  a = F3(1.09);
            System.out.println(a);
            jTextField5.setText(decimalNumb(a, Ndeci));
            
        } else if(n == 1)
        {
            Double a = F3(1.1);
            System.out.println(a);
            jTextField5.setText(decimalNumb(a, Ndeci));
            
        } else if (n == 2)
        {
            Double a = F3(1.11);
            System.out.println(a);
            jTextField5.setText(decimalNumb(a, Ndeci));
            
        }else 
        {
            System.out.println(" it apear there is  a problem ");
        }
          
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    
    
    
    
    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    
    
    
    // X user input part
    
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
        // function choosen 
        int ntry = (int) jComboBox5.getSelectedIndex();
        // number of decimal 
        int Ndeci = (int) jComboBox4.getSelectedIndex();
        
        boolean trial = false;
        double caca=0.0;
        
        
        
        
            
            try
            {
                
                String SXchoosen = jTextField7.getText(); 
                double Xchoosen = Double.parseDouble(SXchoosen);
                caca = Xchoosen;
                
                
            }
            catch(Exception e)
            {
                //jTextField6.setText(" enter a numerical value ");
                ntry = 4;
                
            }
        
        
         
        System.out.println(ntry);
        
        if(ntry == 0)
        {
            
            double YofCx = F1(caca);
            System.out.println("resulta f1: "+caca);
            
            jTextField6.setText(decimalNumb(YofCx, Ndeci));
            
            
        }else if(ntry == 1)
        {
           
            
            double YofCx = F2(caca);
            System.out.println("resulta f2: "+caca);
            
            jTextField6.setText(decimalNumb(YofCx, Ndeci));
            
        }else if(ntry == 2)
        {
          
            
            double YofCx = F3(caca); 
            System.out.println("resulta f3: "+caca);
            
            jTextField6.setText(decimalNumb(YofCx, Ndeci));
            
        }else
        {
            System.out.println(" problem at result user input part in gui file ");
            jTextField6.setText(" enter a numerical value ");
        }
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    
    
    
    
/////////////////////////////////////////////////////////////////////////////////
    
    
    //ROOT PART THO DEPEND OF THE GRAPH PART 
    
    
/////////////////////////////////////////////////////////////////////////////////
    
    
    
    
    
    //NR
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
        if(FunctionChoosen[0] == 1)
        {
            double root1 = NR1(Temp.get(0), Temp.get(1));
             System.out.println("NR1 root1: "+root1);
            
        }else if (FunctionChoosen[0] == 2)
        {
            double root2 = NR2(Temp.get(0), Temp.get(1));
             System.out.println("NR2 root2: "+root2);
            
        }else if (FunctionChoosen[0] == 3)
        {
            double root3 = NR3(Temp.get(0), Temp.get(1));
             System.out.println("N3 root3: "+root3);
            
        }else
        {
            System.out.println(" NR problem in root part ");
        }
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    //SECANT
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        
        if(FunctionChoosen[0] == 1)
        {
            double root1 = Secant1(Temp.get(0), Temp.get(1));
             System.out.println("Secant1 root1: "+root1);
            
        }else if (FunctionChoosen[0] == 2)
        {
            double root2 = Secant2(Temp.get(0), Temp.get(1));
             System.out.println("Secant2 root2: "+root2);
            
        }else if (FunctionChoosen[0] == 3)
        {
            double root3 = Secant3(Temp.get(0), Temp.get(1));
             System.out.println("Secant3 root3: "+root3);
            
        }else
        {
            System.out.println(" Secant problem in root part ");
        }
        
    }//GEN-LAST:event_jButton12ActionPerformed

    //BISECTION
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        
        if(FunctionChoosen[0] == 1)
        {
            double[] root1 = Bisection1(Temp.get(0), Temp.get(1));
             System.out.println("Bisection1 root1: "+Arrays.toString(root1));
            
        }else if (FunctionChoosen[0] == 2)
        {
            double[] root2 = Bisection2(Temp.get(0), Temp.get(1));
             System.out.println("Bisection2 root2: "+Arrays.toString(root2));
            
        }else if (FunctionChoosen[0] == 3)
        {
            double[] root3 = Bisection3(Temp.get(0), Temp.get(1));
             System.out.println("Bisection3 root3: "+Arrays.toString(root3));
            
        }else
        {
            System.out.println(" Bisection problem in root part ");
        }
        
    }//GEN-LAST:event_jButton13ActionPerformed

    //MY WAY
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        
        if(FunctionChoosen[0] == 1)
        {    // would zork but don't use linked likst qnd work only for square function
            //double root1 = MyWay(-1, 1, 0);
            LinkedList<Double> root1 = MyWay2(Temp.get(0), Temp.get(1), 1);
            System.out.println("MyWay2 root1"+root1);
            
        }else if (FunctionChoosen[0] == 2)
        {
            LinkedList<Double> root2 = MyWay2(Temp.get(0), Temp.get(1), 2);
             System.out.println("MyWay2 root2"+root2);
            
        }else if (FunctionChoosen[0] == 3)
        {
            LinkedList<Double> root3 = MyWay2(Temp.get(0), Temp.get(1), 3);
             System.out.println("MyWay2 root3"+root3);
            
        }else
        {
            System.out.println(" MyWay problem in root part ");
        }
        
    }//GEN-LAST:event_jButton14ActionPerformed

    
    
    
    
///////////////////////////////////////////////////////////////////////////////// 
    
    
    
/////////////////////////////////////////////////////////////////////////////////
    
    
    
    
    
    
   
    
  
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

    private String decimalNumb(Double i, int f) 
    {
    
        if(f == 0)
        {
            String a = Double.toString(i);
            return a;
        } else if(f == 1)
        {
            DecimalFormat numberFormat = new DecimalFormat("#.0");
            System.out.println(numberFormat.format( i ));
            String a = numberFormat.format(i);
            return a;
            
        }else if(f == 2)
        {
            DecimalFormat numberFormat = new DecimalFormat("#.00");
            System.out.println(numberFormat.format( i ));
            String a = numberFormat.format(i);
            return a;
            
        }else if(f == 3)
        {
            DecimalFormat numberFormat = new DecimalFormat("#.000");
            System.out.println(numberFormat.format( i ));
            String a = numberFormat.format(i);
            return a;
            
        }else if(f == 4)
        {
            DecimalFormat numberFormat = new DecimalFormat("#.0000");
            System.out.println(numberFormat.format( i ));
            String a = numberFormat.format(i);
            return a;
            
        }else if(f == 5)
        {
            DecimalFormat numberFormat = new DecimalFormat("#.00000");
            System.out.println(numberFormat.format( i ));
            String a = numberFormat.format(i);
            return a;
            
        }else
        {
            String a = Double.toString(i);
            return a;
        }
        
        
    }
    
    
    private double minY()
    {
        
        double tryout1 = Y.get(0);
        int tryout3 = 0;
        int RsizeY = 0;
        int sizeY = Y.size();
        
       
        
        boolean barnabe = true ;
        while(barnabe == true)
         {
             //System.out.println(RsizeY);
             //System.out.println(sizeY);
             
             if(RsizeY == sizeY)  
             {
               //System.out.println("min list Y in GUI button f(x)=x-x^2  suposidly found");
                 return tryout1; 
             } 
             
             if (Y.contains(NEGATIVE_INFINITY))
              {  
                  tryout1 = NEGATIVE_INFINITY;
                  return tryout1;     
              }
             
                             
                 
             if(tryout1 >= Y.get(tryout3) && Y.get(tryout3) != NaN) 
             {  
                 //System.out.println("tryout1: "+ tryout1 +" >= "+ Y.get(tryout3));
             
                 tryout1 = Y.get(tryout3);
                 //System.out.println("pass by here print "+ tryout1);
                 //tryout3++;
                 
             } 
             
             tryout3++;   
             RsizeY++;
                 
             
         }
        
        //System.out.println("sizeY: "+sizeY);
        //System.out.println("tryout1: "+tryout1);
        return tryout1;
    
    
    }
    
    
    
    
    
    
        
    private double maxY()
    {
        
        double tryout1 = Y.get(0);
        int tryout3 = 0;
        int RsizeY = 0;
        int sizeY = Y.size();
        
        int i = 0;
        
        
       
        
        boolean barnabe = true ;
        while(barnabe == true)
         {
             //System.out.println("RsizeY: "+RsizeY);
             //System.out.println("sizeY: "+sizeY);
             
             //System.out.println("tryout1= "+tryout1);
             
             

             
             
             if(RsizeY == sizeY)  
             {
               //System.out.println("min list Y in GUI button f(x)=x-x^2  suposidly found");
                 return tryout1; 
             } 
             
             else if (Y.contains(POSITIVE_INFINITY))
              {  
                  tryout1 = POSITIVE_INFINITY;
                  return tryout1;     
              }
             
                             
                 
             else if(tryout1 <= Y.get(tryout3) && Y.get(tryout3) != NaN) 
             {  
                 //System.out.println("tryout1: "+ tryout1 +" >= "+ Y.get(tryout3));
             
                 tryout1 = Y.get(tryout3);
                 //System.out.println("pass by here print "+ tryout1);
                 //tryout3++;
                 
             }else 
             {
                 //System.out.println("went throught the else");
                 
                 while(Double.isNaN(tryout1))
                 { 
                     //System.out.println("went here");
                     
                     tryout1 = Y.get(i);
                     i++;
                 }
                 //System.out.println("tryout1= "+tryout1);
                 
                 
             
             }
             
             tryout3++;   
             RsizeY++;
                 
             
         }
        
        //System.out.println("sizeY: "+sizeY);
        //System.out.println("tryout1: "+tryout1);
        return tryout1;
    
    
    }
    
    
    
    
    
    
        
//    private double maxY()
//    {
//        
//        double tryout1 = Y.get(0);
//        int tryout3 = 0;
//        int RsizeY = 0;
//        int sizeY = Y.size();
//        
//       
//        
//        boolean barnabe = true ;
//        while(barnabe == true)
//         {
//             //System.out.println(RsizeY);
//             //System.out.println(sizeY);
//             
//                          if (Y.contains(POSITIVE_INFINITY))   
//             {
//                 tryout1 = POSITIVE_INFINITY;
//                 System.out.println("second return ");
//                 return tryout1;
//             }
//             
//             while(Y.get(tryout3) == NaN)   
//             {
//                 System.out.println("went here");
//                 tryout3++;
//             }
//             
//             
//             
//             
//             
//             if(Y.get(tryout3) != NaN)
//             {
//                 if(tryout1 <= Y.get(tryout3))
//                 {
//                     System.out.println("tryout1: "+ tryout1 +" <= "+ Y.get(tryout3));
//                     tryout1 = Y.get(tryout3);
//                 
//                    //System.out.println("pass by here print "+ tryout1);
//                    //tryout3++;
//                 }
//             }
//             
//             
//             
//             
//             if(RsizeY == sizeY)
//             
//                  {
//                      //System.out.println("max list Y in GUI button f(x)=x-x^2  suposidly found");
//                      System.out.println("first return ");
//                      return tryout1;
//                  } 
//             
//             
//             
//
//             
//             
//             tryout3++;
//             RsizeY++; 
//              
//            
//        
//         }
//        
//        System.out.println("third return ");
//        return tryout1;
//    
//    
//    }

    
    
    
    
}
