/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javacoursework1555;


import static java.lang.Double.NEGATIVE_INFINITY;
import static java.lang.Double.NaN;
import static java.lang.Double.POSITIVE_INFINITY;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import static javacoursework1555.Functions.F1;
import static javacoursework1555.Functions.F2;
import static javacoursework1555.Functions.F3;
import static javacoursework1555.subMenu.step1;

//import javacoursework1555.Plot2d;



/**
 *
 * @author barnabe
 */
public class GUI extends javax.swing.JFrame {

    /** Creates new form GUI */
    public GUI() {
        initComponents();
        
       
        
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        
//         while(n1 <= sizeX)
//         {
//             double a = X.get(n1);
//             X1[n1] = a;
//         
//         }
//         
//         while(n2 <= sizeY)
//         {
//             double b = X.get(n2);
//             Y1[n2] = b;
//         }
    


            

    }

    ArrayList<Double> Temp = new ArrayList<Double>();
    ArrayList<ArrayList<Double>> XY = new ArrayList<ArrayList<Double>>();
   
    ArrayList<Double> X = new ArrayList<Double>();
//    double [] X1;
//    int sizeX = X.size();
//    int n1 = 0;
    
   
    
    
    ArrayList<Double> Y = new ArrayList<Double>();
//    double [] Y1;
//    int sizeY = Y.size();
//    int n2 = 0;
//    
    
   
    
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame0");
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Result");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton3.setText("comfirm range");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButton2.setText("graph");
        jButton2.setActionCommand("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("f(x)=x-x^2");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("f(x)=ln(x+1)+1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("f(x)=e^x-3x");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-1", "0.5" , "0.50001", "0.49999" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "-1", "-1.0e-10" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.09", "1.1", "1.11" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton7.setText("f(x)=x-x^2");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("f(x)=ln(x+1)+1");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("f(x)=e^x-3x");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel1.setText("number of decimal :");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "not choosing", "1", "2", "3","4" ,"5"}));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(144, 144, 144))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ///result
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        
           
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    
   ///graph
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        jPanel2.setVisible(true);
        jPanel4.setVisible(false);
        
        
    
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
    
    
    
    /// GRAPH PART
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    
    /// comfirm range
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        jPanel3.setVisible(true);
        
        
        try      
        {            
            String g1 = jTextField1.getText(); 
            double d1 = Double.parseDouble(g1);
                         
            String g2 = jTextField2.getText();
            double d2 = Double.parseDouble(g2);
                        
                            
            //System.out.println(d1 +" "+ d2);    
            if(d1 > d2)     
            {           
                System.out.println("you can't enter an impossible range ");       
            }    
            else  
            {   
                Temp.add(0, d1);   
                Temp.add(1, d2); 
                System.out.println("range: for x:" + Temp.get(0) +" to x: "+ Temp.get(1));
            }
                    
        } catch(Exception e)
                    
        {
            System.out.println(" the number you entered isn't valide ");          
        }
    
            
        
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    
    ///graph - f(x) = x-x^2
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         
        int k = 1; 
              
        double k1 = Temp.get(0);  
        double k2 = Temp.get(1);
              
        //System.out.println(k1 +" "+ k2);
              

        step1( k, k1, k2);  
        //System.out.println("print of step1() in GUI for f(x)=x-x^2   "+step1( k, k1, k2));
        XY = (step1(k, k1, k2));
        //System.out.println("print of XY list in GUI wich should be similar to step1() button selected f(x)=x-x^2  "+XY);
        X = XY.get(0);
        System.out.println("print of X list which should be similar to step1() first part button selected f(x)=x-x^2   "+X);
        Y = XY.get(1);
        System.out.println("print of Y list which should be similar to step1() first part button selected f(x)=x-x^2  "+Y);
        
        double minimumY = minY();
        System.out.println("min for f(x)=x-x^2 : "+minimumY);
        
        double maximumY = maxY();
        System.out.println("max for f(x)=x-x^2 : "+maximumY);
        
        
        
       //Plot2d T1 = new Plot2d(X1, Y1);
       
        
    }//GEN-LAST:event_jButton4ActionPerformed

    ///graph - f(x) = ln(x+1)+ 1
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
      int k = 2; 
              
      double k1 = Temp.get(0);
      double k2 = Temp.get(1);
              
      //System.out.println(k1 +" "+ k2);
              
      step1( k, k1, k2);
      //System.out.println("print of step1() in GUI for f(x)=ln(x+1)+1   "+ step1( k, k1, k2));
      XY = (step1(k, k1, k2));
      //System.out.println("print of XY list in GUI wich should be similar to step1() button selected f(x)=ln(x+1)+1  "+XY);
      X = XY.get(0);
      System.out.println("print of X list which should be similar to step1() first part button selected f(x)=ln(x+1)+1   "+ X);
      Y = XY.get(1);
      System.out.println("print of Y list which should be similar to step1() first part button selected f(x)=ln(x+1)+1  "+Y);
      
        
        double minimumY;
        double maximumY;
        
        double Ninfinite = Y.indexOf(NEGATIVE_INFINITY);//  value of infinity in Y for -infinty
        double Pinfinite = Y.indexOf(POSITIVE_INFINITY);//  value of infinity in Y for +infinty
        
        minimumY = minY();
        System.out.println("min: "+minimumY);
        maximumY = maxY();
        System.out.println("max: "+maximumY);
        
        
        
//        if (Y.contains(NEGATIVE_INFINITY))
//        {
//        
//            System.out.println("min for f(x)=ln(x+1)+1 : "+NEGATIVE_INFINITY+"in X = "+X.get((int)Ninfinite));
//            minimumY = NEGATIVE_INFINITY;
//            maximumY = maxY();
//            System.out.println("max for f(x)=ln(x+1)+1 : "+maximumY);
//            
//        }else if (Y.contains(POSITIVE_INFINITY))
//        {
//        
//            System.out.println("max for f(x)=ln(x+1)+1 : "+POSITIVE_INFINITY+"in X = "+X.get((int)Pinfinite));
//            maximumY = POSITIVE_INFINITY;
//            minimumY = minY();
//            System.out.println("min for f(x)=ln(x+1)+1 : "+minimumY);
//        
//        }else if(Y.contains(NEGATIVE_INFINITY) || Y.contains(POSITIVE_INFINITY))
//        {
//        
//            System.out.println("min for f(x)=ln(x+1)+1 : "+NEGATIVE_INFINITY+"in X = "+Y.get((int)Ninfinite));
//            minimumY = NEGATIVE_INFINITY;
//            System.out.println("max for f(x)=ln(x+1)+1 : "+POSITIVE_INFINITY+"in X = "+Y.get((int)Pinfinite));
//            maximumY = POSITIVE_INFINITY;
//            
//        }else
//        {
//        
//            minimumY = minY();
//            System.out.println("min for f(x)=ln(x+1)+1 : "+minimumY);
//            
//            maximumY = maxY();
//            System.out.println("max for f(x)=ln(x+1)+1 : "+maximumY);
//        
//        }

        

        
        
        /*System.out.println(" X value of -Infinity: "+Ninfinite);
        System.out.println("Y value for Ninfinite: "+Y.get((int) Ninfinite));
        System.out.println(" X value of +Infinity: "+Pinfinite);*/
        
        

      
      
      //Plot2d T1 = new Plot2d(X1, Y1);
      
       
    }//GEN-LAST:event_jButton5ActionPerformed

    ///graph - f(x) = e^x-3x
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        int k = 3; 
        
        double k1 = Temp.get(0);
        double k2 = Temp.get(1);
              
        //System.out.println(k1 +" "+ k2);
        step1( k, k1, k2);
        //System.out.println("print of step1() in GUI for f(x)=e^x-3x   "+ step1( k, k1, k2));
        XY = (step1(k, k1, k2));
        //System.out.println("print of XY list in GUI wich should be similar to step1() button selected f(x)=e^x-3  "+XY);
        X = XY.get(0);
        System.out.println("print of X list which should be similar to step1() first part button selected f(x)=e^x-3   "+ X);
        Y = XY.get(1);
        System.out.println("print of Y list which should be similar to step1() first part button selected f(x)=e^x-3  "+ Y);
        
        //Plot2d T1 = new Plot2d(X1, Y1);
        
        double minimumY = minY();
        System.out.println("min for f(x)=e^x-3 : "+minimumY);
        
        double maximumY = maxY();
        System.out.println("max for f(x)=e^x-3 : "+maximumY);      

        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    
    
   
    
    
/////////////////////////////////////////////////////////////////////////////////    
    
    
    
    
    
    
    
    ////RESULT PART
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

 
    
    ///result - f(x) = x-x^2 <- combobox1 is where the x asked are located
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //int n = 0 ;
        int n = (int) jComboBox1.getSelectedIndex();
        int Ndeci = (int) jComboBox4.getSelectedIndex();
        //System.out.println(n);
        
        if(n == 0)
        {
            Double  a = F1(-1.0);
            System.out.println(a);
            jTextField3.setText(decimalNumb(a, Ndeci));
            
            
        } else if(n == 1)
        {
            Double a = F1(0.5);
            System.out.println(a);
            jTextField3.setText(decimalNumb(a, Ndeci));
            
        } else if (n == 2)
        {
            Double a = F1(0.50001);
            System.out.println(a);
            jTextField3.setText(decimalNumb(a,Ndeci));
            
        } else if (n == 3)
        {
            Double a = F1(0.49999);
            System.out.println(a); 
            jTextField3.setText(decimalNumb(a, Ndeci));
            
        } else 
        {
            System.out.println(" it apear there is  a problem ");
        }
                
        
    }//GEN-LAST:event_jButton7ActionPerformed
     
    ///result - f(x) = ln(x+1)+ 1 <- combobox2 is where the x asked are located
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        int n = (int) jComboBox2.getSelectedIndex();
        int Ndeci = (int) jComboBox4.getSelectedIndex();
        //System.out.println(n);
        
        if(n == 0)
        {
            Double  a = F1(0.0);
            System.out.println(a);
            jTextField4.setText(decimalNumb(a, Ndeci));
            
        } else if(n == 1)
        {
            Double a = F1(-1.0);
            System.out.println(a);
            jTextField4.setText(decimalNumb(a, Ndeci));
            
        } else if (n == 2)
        {
                            /// -1.0e-10
            Double a = F1(-12.7182818285);
            System.out.println(a);
            jTextField4.setText(decimalNumb(a, Ndeci));
            
        }else 
        {
            System.out.println(" it apear there is  a problem ");
        }
          
        
    }//GEN-LAST:event_jButton8ActionPerformed
     
    ///result - f(x) = e^x-3x <- combobox3 is where the x asked are located
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
        int n = (int) jComboBox3.getSelectedIndex();
        int Ndeci = (int) jComboBox4.getSelectedIndex();
        //System.out.println(n);
        
        if(n == 0)
        {
            Double  a = F1(1.09);
            System.out.println(a);
            jTextField5.setText(decimalNumb(a, Ndeci));
            
        } else if(n == 1)
        {
            Double a = F1(1.1);
            System.out.println(a);
            jTextField5.setText(decimalNumb(a, Ndeci));
            
        } else if (n == 2)
        {
            Double a = F1(1.11);
            System.out.println(a);
            jTextField5.setText(decimalNumb(a, Ndeci));
            
        }else 
        {
            System.out.println(" it apear there is  a problem ");
        }
          
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox4ActionPerformed

    
  
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    private String decimalNumb(Double i, int f) 
    {
    
        if(f == 0)
        {
            String a = Double.toString(i);
            return a;
        } else if(f == 1)
        {
            DecimalFormat numberFormat = new DecimalFormat("#.0");
            System.out.println(numberFormat.format( i ));
            String a = numberFormat.format(i);
            return a;
            
        }else if(f == 2)
        {
            DecimalFormat numberFormat = new DecimalFormat("#.00");
            System.out.println(numberFormat.format( i ));
            String a = numberFormat.format(i);
            return a;
            
        }else if(f == 3)
        {
            DecimalFormat numberFormat = new DecimalFormat("#.000");
            System.out.println(numberFormat.format( i ));
            String a = numberFormat.format(i);
            return a;
            
        }else if(f == 4)
        {
            DecimalFormat numberFormat = new DecimalFormat("#.0000");
            System.out.println(numberFormat.format( i ));
            String a = numberFormat.format(i);
            return a;
            
        }else if(f == 5)
        {
            DecimalFormat numberFormat = new DecimalFormat("#.00000");
            System.out.println(numberFormat.format( i ));
            String a = numberFormat.format(i);
            return a;
            
        }else
        {
            String a = Double.toString(i);
            return a;
        }
        
        
    }
    
    
    private double minY()
    {
        
        double tryout1 = Y.get(0);
        int tryout3 = 0;
        int RsizeY = 0;
        int sizeY = Y.size();
        
       
        
        boolean barnabe = true ;
        while(barnabe == true)
         {
             //System.out.println(RsizeY);
             //System.out.println(sizeY);
             
             if(RsizeY == sizeY)
             
                  {
                      //System.out.println("min list Y in GUI button f(x)=x-x^2  suposidly found");
                      return tryout1;
                  } 
             
                     if (Y.contains(NEGATIVE_INFINITY))
                     {               
        
                         tryout1 = NEGATIVE_INFINITY;
                         
                         return tryout1;
                         
                     }
             
                             
                 if(tryout1 >= Y.get(tryout3) || Y.get(tryout3) != NaN)
                 {  
                     tryout1 = Y.get(tryout3);
                 
                     
                
                 //System.out.println("pass by here print "+ tryout1);
                 //tryout3++;
                 } 
                 
                 tryout3++;
                 RsizeY++;
                 
             
              
             
             
               
//             System.out.println("tryout3: "+tryout3);
//             System.out.println("Rsize: "+RsizeY);
//             System.out.println("value in Y of tryout3: "+Y.get(tryout3));
              
            
        
         }
        //System.out.println(sizeY);
        System.out.println(tryout1);
        return tryout1;
    
    
    }
    
        private double maxY()
    {
        
        double tryout1 = Y.get(0);
        int tryout3 = 0;
        int RsizeY = 0;
        int sizeY = Y.size();
        
       
        
        boolean barnabe = true ;
        while(barnabe == true)
         {
             //System.out.println(RsizeY);
             //System.out.println(sizeY);
             
             if(RsizeY == sizeY)
             
                  {
                      //System.out.println("max list Y in GUI button f(x)=x-x^2  suposidly found");
                      return tryout1;
                  } 
             
             
             
             if (Y.contains(POSITIVE_INFINITY))   
             {
                 tryout1 = POSITIVE_INFINITY;
                 return tryout1;
             }
             
             
             
             if(tryout1 <= Y.get(tryout3) || Y.get(tryout3) != NaN)
         
             {
                 tryout1 = Y.get(tryout3);
                 
                 
             
                
                 //System.out.println("pass by here print "+ tryout1);
                 //tryout3++;
                  
             }
             
             tryout3++;
             RsizeY++; 
              
            
        
         }
        return tryout1;
    
    
    }

    
    
    
    
}
